### ISSUE TITLE
Swift 4 and Package Manager v4

### ISSUE THREAD

**Issue by JohanDufau** [SwiftAndroid/swift-jni#2]
Hello,

If you are interested, we did a portage of this lib to Swift 4 with a Swift PM v4 integration here:
https://github.com/Creatiwity/JNISwift

Thanks for the work!
Johan

**Comment by ephemer** [comment]
Hi Johan, thanks for the link. Does this mean you have Swift 4 with Dispatch running on Android? Do you have any more information about building etc.? I was under the impression that there were some issues in building Swift 4 for Android.

Would you be interested in making a pull request out of your changes?

I'd also appreciate if you gave notice in your repo about the original author / licence. Obviously most of this is just wrapping code but there is a bunch of my original work in there, especially in `SwiftJNI.swift`. Thanks!

**Comment by JohanDufau** [comment]
Hello Geordie,
We almost managed to have Dispatch and Foundation running. We have a small issue left. Once we have finished the job, I'll send you the link to a usable toolchain.

I'll try to make the PR as soon as I get some times.

Sorry for the lack of quotation, it was totally unintended. It is now fixed in the README.

**Comment by ephemer** [comment]
Great, thanks! I'd also be interested in the invocations you've used to build just Swift 4/SwiftPM - would like to make some PRs on the original repo but was warned away from trying to build it with the current documentation.
